---
title: "Test Animation in R"
author: "John Minter based on Yihui Xie"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadLibraries}
library(animation)
```


# Setup a simple animation

## set some options first

```{r setOptions}
ani.options(interval = 0.2, nmax = 10)
## use a loop to create images one by one
for (i in 1:ani.options('nmax')) {
  plot(rnorm(30))
  ani.pause()   ## pause for a while ('interval')
}
```

## restore the options

  see `?ani.record` for an alternative way to set up an animation

# Animations in HTML

```{r saveHTML}
saveHTML({
  ani.options(interval = 0.05, nmax = 30)
  par(mar = c(3, 3, 2, 0.5), mgp = c(2, .5, 0), tcl = -0.3,
      cex.axis = 0.8, cex.lab = 0.8, cex.main = 1)
  brownian.motion(pch = 21, cex = 5, col = 'red', bg = 'yellow',
                  main = 'Demonstration of Brownian Motion')
}, img.name = 'bm_plot', title = 'Demonstration of Brownian Motion',
         description = c('Random walk on the 2D plane: for each point',
                         '(x, y), x = x + rnorm(1) and y = y + rnorm(1).'))
```

# GIF animations

```{r difAnimation}
saveGIF({
  ani.options(nmax = 30)
  brownian.motion(pch = 21, cex = 5, col = 'red', bg = 'yellow')
}, interval = 0.05,
movie.name = 'bm_demo.gif', ani.width = 600, ani.height = 600)
```


